source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

use_frameworks!

target 'Swift_Study_01' do
	pod 'Alamofire'
	pod 'SnapKit'
	pod 'RxSwift', '~> 5'
    	pod 'RxCocoa', '~> 5'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end

